name: 01-ports-add
services:
  web:
    image: nginx
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8080
        published: "8080"
        protocol: tcp
      - mode: ingress
        target: 5000
        published: "5000"
        protocol: tcp
networks:
  default:
    name: 01-ports-add_default
