name: 02-ports-override
services:
  web:
    image: nginx
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8080
        published: "80"
        protocol: tcp
networks:
  default:
    name: 02-ports-override_default
